# Generated by Django 3.2.4 on 2021-08-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=160)),
                ('amount', models.IntegerField()),
                ('salesman_assigned', models.CharField(max_length=100)),
                ('delivery_date', models.DateField()),
                ('mobile_number', models.CharField(max_length=12)),
                ('tailor_assigned', models.CharField(max_length=100)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
