# Generated by Django 3.2.4 on 2021-08-02 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_received',
            field=models.DateField(default=datetime.datetime(2021, 8, 2, 16, 21, 59, 499798)),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='balance',
            field=models.CharField(max_length=100),
        ),
    ]
