# Generated by Django 3.2.4 on 2021-08-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0003_alter_order_order_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_received',
            field=models.DateField(auto_now=True),
        ),
    ]
