# Generated by Django 3.2.4 on 2021-08-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0004_alter_order_order_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
