# Generated by Django 3.2.4 on 2021-08-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0005_auto_20210804_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(max_length=12),
        ),
    ]
