# Generated by Django 3.2.4 on 2021-08-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0006_alter_order_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addtailor',
            fields=[
                ('tailorid', models.AutoField(primary_key=True, serialize=False)),
                ('tailorname', models.CharField(max_length=20)),
            ],
        ),
    ]
