# Generated by Django 3.2.4 on 2021-08-23 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0007_addtailor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtailor',
            old_name='tailorname',
            new_name='tailor_name',
        ),
    ]
