# Generated by Django 3.2.4 on 2021-08-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0008_rename_tailorname_addtailor_tailor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='serial_number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
