# Generated by Django 3.2.8 on 2021-10-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0009_order_serial_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='balance',
            new_name='advance',
        ),
    ]
