# Generated by Django 3.2.8 on 2021-10-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0010_rename_balance_order_advance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addtailor',
            new_name='tailor',
        ),
    ]
