# Generated by Django 3.2.8 on 2021-11-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0011_rename_addtailor_tailor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=50)),
                ('order_name', models.CharField(max_length=160)),
                ('amount', models.IntegerField()),
                ('salesman_assigned', models.CharField(max_length=100)),
                ('delivery_date', models.DateField()),
                ('mobile_number', models.CharField(max_length=12)),
                ('tailor_assigned', models.CharField(max_length=100)),
                ('advance', models.IntegerField()),
                ('order_completed', models.DateField(auto_now=True)),
            ],
        ),
    ]
