# Generated by Django 3.2.8 on 2021-11-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0012_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completed',
            old_name='delivery_date',
            new_name='booking_date',
        ),
    ]
